image: Visual Studio 2019
clone_folder: c:\gopath\src\github.com\%APPVEYOR_REPO_NAME%

# trigger build/deploy only on tag
# if false, take care that %APPVEYOR_REPO_TAG_NAME% won t be set on commit
# this will fail the build
skip_non_tags: true

environment:
  GOPATH: c:\gopath
  JFROG_CLI_OFFER_CONFIG: false
  VCS_URL: https://github.com/%APPVEYOR_REPO_NAME%

install:
  - set PATH=%WIX%\bin;%PATH%
  - set PATH=%GOPATH%\bin;%PATH%
  - go install github.com/goreleaser/goreleaser@latest
  - choco install go-msi -y

build_script:
  - goreleaser build --snapshot --rm-dist --id windows
  - refreshenv
  - set PATH=%WIX%\bin;%PATH%
  - set GH_APP=%APPVEYOR_PROJECT_NAME%
  - set GH_USER=%APPVEYOR_ACCOUNT_NAME%
  - set VERSION=%APPVEYOR_REPO_TAG_NAME%
  - set GOARCH=386
  - copy .\dist\windows_windows_386\circuitblocks-agent.exe %MYAPP%.exe
  - copy .\dist\windows_windows_386\circuitblocks-agent.exe .\dist\circuitblocks-agent.exe
  - copy .\dist\windows_windows_386\circuitblocks-agent.exe .\dist\circuitblocks-agent.exe-temp
  - go-msi set-guid
  - go-msi make --msi %GH_APP%-windows.msi --version %VERSION% --arch %GOARCH% -s ./templates

after_deploy:
  # Choco push
  # - .\go-msi.exe choco --input %GH_APP%-%GOARCH%.msi --version %VERSION% --changelog-cmd "changelog ghrelease --version %VERSION%"
  # - choco push -k="'%CHOCOKEY%'" %GH_APP%.%VERSION%.nupkg
  # Bintray push
  # - never-fail jfrog bt pc --user %GH_USER% --key %BT_KEY% --licenses=MIT --vcs-url=https://github.com/%APPVEYOR_REPO_NAME% %GH_USER%/msi/%GH_APP%
  # - jfrog bt upload --user %GH_USER% --key %BT_KEY%  --override=true --publish=true %GH_APP%-%GOARCH%-%VERSION%.msi %GH_USER%/msi/%GH_APP%/%VERSION%
  # - never-fail jfrog bt pc --user %GH_USER% --key %BT_KEY% --licenses=MIT --vcs-url=https://github.com/%APPVEYOR_REPO_NAME% %GH_USER%/choco/%GH_APP%
  # - jfrog bt upload --user %GH_USER% --key %BT_KEY%  --override=true --publish=true %GH_APP%.%VERSION%.nupkg %GH_USER%/choco/%GH_APP%/%VERSION%

# to disable automatic tests
test: off

# need this to deploy assets,
# note that each MUST match only one file
artifacts:
  - path: "*.msi"
    name: msi

# deploy section to github releases
deploy:
  - provider: GitHub
    artifact: msi
    draft: false
    prerelease: false
    description: "Release for Windows"
    auth_token:
      secure: flZLfcgYxpArNKvwHHKKz+TNv6Gam/FZGQisYhWBnvZQTAGLpXKBTstk0h83vDox
    on:
      branch:
        - master
        - /v\d\.\d\.\d/
        - /\d\.\d\.\d/
      appveyor_repo_tag: true
